more updates

diff --git a/systemd/S30sureshot b/systemd/S30sureshot
--- a/systemd/S30sureshot
+++ b/systemd/S30sureshot
@@ -3,60 +3,65 @@
 DAEMON="sureshot"
 PIDFILE="/var/run/$DAEMON.pid"
 
-SYSLOGD_ARGS="-tbP"
-
 # HACK: kind of a hack to do it here, but the OS is limited
 # and I'd need to just create another file like this to do it
 #
 # install module into the kernel we need for USB serial connection
 modprobe ftdi_sio
 
+# Allow a few customizations from a config file if we want
+test -r /etc/default/$DAEMON && . /etc/default/$DAEMON
 
-# shellcheck source=/dev/null
-[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"
+# move to our working directory
+[ -z "$WD" ] && $WD = "/code/sureshot"
+cd $WD
 
 # BusyBox' syslogd does not create a pidfile, so pass "-n" in the command line
 # and use "-m" to instruct start-stop-daemon to create one.
 start() {
+    MPF_ARGS="$MPF_ARGS -tbP"
+
     printf 'Starting %s: ' "$DAEMON" 
-    # shellcheck disable=SC2086 # we need the word splitting
-    start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/bin/mpf" \
-            -- -n $SYSLOGD_ARGS
+    umask 077
+    start-stop-daemon -S -q -p $PIDFILE \
+        --exec /usr/bin/mpf -- $MPF_ARGS
+    
     status=$?
     if [ "$status" -eq 0 ]; then
-            echo "OK"
+        echo "OK"
     else
-            echo "FAIL"
+        echo "FAIL"
     fi
     return "$status"
 }
 
 stop() {
-    printf 'Stopping %s: ' "$DAEMON"
-    start-stop-daemon -K -q -p "$PIDFILE"
-    status=$?
-    if [ "$status" -eq 0 ]; then
-            rm -f "$PIDFILE"
-            echo "OK"
-    else
-            echo "FAIL"
-    fi
-    return "$status"
+    printf 'Stopping %s: ' "$DAEMON" 
+    start-stop-daemon -K -q -p $PIDFILE
+    [ $? = 0 ] && echo "OK" || echo "FAIL"
+}
+restart() {
+    stop
+    start
 }
 
-restart() {
+:restart() {
     stop
     sleep 1
     start
 }
 
 case "$1" in
-    start|stop|restart)
-            "$1";;
-    reload)
-            # Restart, since there is no true "reload" feature.
-            restart;;
-    *)
-            echo "Usage: $0 {start|stop|restart|reload}"
-            exit 1
+  start)
+        start
+        ;;
+  stop)
+        stop
+        ;;
+  restart|reload)
+        restart
+        ;;
+  *)
+        echo "Usage: $0 {start|stop|restart}"
+        exit 1
 esac
